import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";

import { getConfig } from "../wagmi";
import { Providers } from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
import React from "react";
import { Toaster } from "react-hot-toast";

const lato = Lato({
    subsets: ["latin"],
    variable: "--font-lato",
    weight: "400",
});
export const metadata: Metadata = {
    description: "Generated by create-wagmi",
    title: "Create Wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
    const initialState = cookieToInitialState(
        getConfig(),
        headers().get("cookie")
    );
    return (
        <html lang="en">
            <body className={`${lato.variable} font-sans antialiased`}>
                <Providers initialState={initialState}>
                    <Toaster />
                    {props.children}
                </Providers>
            </body>
        </html>
    );
}
